pipeline {
    agent any
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('docker-hub-credentials')
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package -DskipTests'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Docker Build & Push') {
            steps {
                bat 'withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', 
                                                      usernameVariable: 'DOCKER_HUB_USERNAME', 
                                                      passwordVariable: 'DOCKER_HUB_PASSWORD')])'

                 bat 'docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD} ${DOCKER_HUB_REGISTRY}'
                 bat 'docker build -t tharun2258/java-app:latest .'
                 bat 'docker push ${REGISTRY}/java-app/latest'                                    
              
            }
        }
        stage('Deploy to Minikube') {
            steps {
                sh 'helm upgrade --install java-app helm/ --set image.tag=latest'
            }
        }
    }
}